# Welcome to "Crush Python"

God has saved us and called us to a holy life - not because of anythin we have done but because of his own purpose and grace. This grace was given us in Christ Jesus before the beginning of time. (1Tim1:9)

하나님이 우리를 구원하사 거룩하신 소명으로 부르심은 우리의 행위대로 하심이 아니요 오직 자기 뜻과 영원 전부터 그리스도 예수 안에서 우리에게 주신 은혜대로 하심이라. (딤후1:9)

----------

### Some Excellent Machine Learning Technical Video Lectures Recommended

1. [Neural Networks](https://www.youtube.com/watch?v=aircAruvnKk&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi)
    - link: [YouTube](https://www.youtube.com/watch?v=aircAruvnKk&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi)
    - length: 19:13
    - lecturer: 3Blue1Brown
    - contents: One of the best lecture series about neural networks.
    
1. [Gradient descent](https://www.youtube.com/watch?v=IHZwWFHWa-w&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&index=3&t=0s)
    - link: [YouTube](https://www.youtube.com/watch?v=IHZwWFHWa-w&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&index=3&t=0s)
    - length: 21:00
    - lecturer: 3Blue1Brown
    - contents: One of the best lecture series about neural networks.
    
1. [What is backpropagation really doing?](https://www.youtube.com/watch?v=Ilg3gGewQ5U&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&index=3)
    - link: [YouTube](https://www.youtube.com/watch?v=Ilg3gGewQ5U&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&index=3)
    - length: 13:53
    - lecturer: 3Blue1Brown
    - contents: One of the best lecture series about neural networks.
    
1. [Backpropagation calculus](https://www.youtube.com/watch?v=Ilg3gGewQ5U&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&index=3)
    - link: [YouTube](https://www.youtube.com/watch?v=Ilg3gGewQ5U&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&index=3)
    - length: 10:18
    - lecturer: 3Blue1Brown
    - contents: One of the best lecture series about neural networks.


# [The Monty Hall Problem](http://en.wikipedia.org/wiki/Monty_Hall_problem)

Here's a fun and perhaps surprising statistical riddle, and a good way to get some practice writing python functions.

In a gameshow, contestants try to guess which of 3 closed doors contain a cash prize (goats are behind the other two doors). Of course, the odds of choosing the correct door are 1 in 3. As a twist, the host of the show occasionally opens a door after a contestant makes his or her choice. This door is always one of the two the contestant did not pick, and is also always one of the goat doors (note that it is always possible to do this, since there are two goat doors). At this point, the contestant has the option of keeping his or her original choice, or swtiching to the other unopened door. The question is: is there any benefit to switching doors? The answer surprises many people who haven't heard the question before.

We can answer the problem by running simulations in Python. We'll do it in several parts.


In [ ]:
from IPython.display import YouTubeVideo
YouTubeVideo('mhlc7peGlGg') 

### Refer to another good explanations of Monty Hall Problem in Korean
- [서울대 경영대학원 - 직관과 다른 확률](https://cba.snu.ac.kr/ko/sblcolumn?mode=view&bbsidx=77838)
- [위키피디아](https://ko.wikipedia.org/wiki/%EB%AA%AC%ED%8B%B0_%ED%99%80_%EB%AC%B8%EC%A0%9C)
- [나무위키](https://namu.wiki/w/%EB%AA%AC%ED%8B%B0%20%ED%99%80%20%EB%AC%B8%EC%A0%9C)

## Step 1: (Using list)
First, write a function called `simulate_prizedoor`. This function will simulate the location of the prize in many games -- see the detailed specification below:

In [ ]:
#%%file simulate_prizedoor.py
# simulate_prizedoor.py
# CrushPython - MontyHall
import random                    # to use random.randint(......)

def simulate_prizedoor(nsim):
    """    
    Return a random array or list of 0s, 1s, and 2s. 
    The length of the array or list is the parameter nsim - a positive integer. 
    nsim represents the number of simulation. 
    
    This function generates a random array of 0s, 1s, and 2s, representing 
    hiding a prize between door 0, door 1, and door. 
    
    Use random.randint(0,2) to generate the numbers of 0, 1, and 2 randomly.

    >>> print(simulate_prizedoor(3))
    array([0, 0, 2])
    >>> print(simulate_prizedoor(7))
    [2, 1, 0, 1, 1, 0, 2]
    """
    assert nsim >= 1
    

    return prizedoors

### Step 1: NumPy Impelmentation 

The code shown below does the same thing, but is implemented using numpy array, not list. 

In [ ]:
import numpy as np
import random                    # to use random.randint(......)

def simulate_prizedoor(nsim):
    assert nsim >= 1

    
    
    return prizedoors

#### 질문 1: 
함수 `simulate_prizedoor(5)`을 실행했을 때, 함수가 `[0, 1, 1, 2, 0]`를 반환한다면, 5의 의미는 무엇이며, 반환값 각각의 의미는 무엇입니까? 또한 `simulate_prizedoor()` 함수가 `[1, 1, 1, 1, 1]`같은 값도 반환할 수도 있나요? yes/no로 답하십시오. 

#### 답:
- 
- 

#### 질문 2: 
위의 코드에서 `assert nsim >= 1` 은 무엇을 하는 것이며, 왜 이런 구문이 필요한 것일까요?  

#### 답:
- 
- 

## Step 2: (using list)
Next, write a function `simulate_guess()` that simulates the contestant's guesses for `nsim` simulations. Call this function `simulate_guess`. The specs:

In [ ]:
#%%file simulate_guess.py
# simulate_guess.py
# CrushPython - MontyHall

import random
def simulate_guess(nsim):
    """
    Return an arry of list that is  a strategy for guessing which door 
    a prize is behind. This could be a random strategy, one that always 
    guesses 2, whatever. 
    
    You may use randint() as well here

    nsim is the number of simulations to generate guesses for.

    >>> print(simulate_guess(5))
    array([0, 0, 0, 0, 0])
    >>> print(simulate_guess(5))
    [0, 0, 0, 0, 0]
    """

    assert nsim >= 1

    
    
    return guesses

### Step 2: NumPy Impelmentation 

In [ ]:
def simulate_guess(nsim):
    assert nsim >= 1
    guesses = np.empty(0, dtype=int)
    for num in range(0, nsim):
        answer = random.randint(1, 1)
        guesses = np.append(guesses, answer)
    return guesses

In [ ]:
simulate_guess(5)

#### 질문 3: 
`simulate_guess()`함수는 누구(Show Host or Contestant)의 역할을 감당하는 것을 시뮬레이션 하는 것인가요? 


#### 답:
- 
- 

#### 질문 4: 
`simulate_guess()` 함수를 정의할 때, 왜 "This could be a random strategy, one that always guesses 2, whatever."라고 설명하나요? random strategy로 할 때의 함수 반환값과 다른 경우의 반환값을 각각 `nsim = 7` 일 경우, 나열하십시오. 


#### 답:
- 
- 

## Step 3: 
Next, write a function, `goat_door`, to simulate randomly revealing one of the goat doors that a contestant didn't pick.

In [ ]:
#%%file goat_door.py
# goat_door.py
# CrushPython - MontyHall

import numpy as np
import random

def goat_door(prizedoors, guesses):
    """ Return the goat door that is opened for each simulation. 
    Each item is 0, 1, or 2, and is different from both prizedoors and guesses.
    
    It simulates the opening of a "goat door" that doesn't contain the prize,
        and is different from the contestants guess
    The prizedoors array or list is the door that the prize is behind 
        in each simulation
    The guesses array or list is the door that the contestant guessed 
        in each simulation
        
    remove(element) removes the first matching element from the list.
    pop() removes the last element from the list.

    >>> print(goat_door(np.array([0, 1, 2]), np.array([1, 1, 1])))
    array([2, 2, 0])              # array([2, 0, 0]) is valid too.
    >>> print(goat_door([0, 1, 2], [1, 1, 1]))
    array([2, 2, 0])              # array([2, 0, 0]) is valid too.
    """
    
    goat_door = []

    return goat_door

In [ ]:
goat_door([0, 1, 2], [1, 1, 1])

In [ ]:
print(goat_door(np.array([0, 1, 2, 0, 2]), np.array([1, 1, 1, 1, 1])))

### Step 3: NumPy Impelmentation 

In [ ]:
def goat_door(prizedoors, guesses):
    
    return goat_door

#### 질문 5:

만약 `prizedoors = [0, 1, 2, 1, 2], )`이며, random strtegy로 인하여, `guesses = [1, 2, 0, 1, 0]`이라면, `goat_door()`가 반환하는 값은 무엇입니까? 답이 여러 개라면, 모든 경우를 나열하십시오. 



#### 답:
```
- [2, 0, 1, 0, 1]
- [2, 0, 1, 1, 1]
```

## Step 4: 
Write a function, `switch_guess`, that represents the strategy of always switching a guess after the goat door is opened.

In [ ]:
# %load switch_guess.py
#%%file switch_guess.py
# CrushPython - MontyHall

def switch_guess(guesses, goatdoors):
    """ Return the new door after switching. Should be different from 
    both guesses and goatdoors.
    The parameter guesses is an array or list of original guesses for 
        each simulation 
    The parameter goatdoors is an array or list of revealed goat doors for 
        each simulation
    The strategy that always switches a guess after the goat door is opened
    
    remove(element) removes the first matching element from the list.
    pop() removes the last element from the list.
    
    >>> print(switch_guess(np.array([0, 1, 2]), np.array([1, 2, 1])))
    [2, 0, 0]                      # [2, 0, 0] is valid
    >>> print(switch_guess([0, 1, 2], [1, 2, 1]))
    [2, 0, 0]                      # [2, 0, 0] is valid
    """
    switchguess = []

    
    return switchguess

In [ ]:
switch_guess([0, 1, 2], [1, 2, 1])

In [ ]:
switch_guess(np.array([1, 1, 1]), np.array([2, 0, 0]))

### Step 4: NumPy Impelmentation 

In [ ]:
def switch_guess(guesses, goatdoors):
    
    return switchguess

#### 질문 6:

만약, `switch_guess(guesses = [0, 1, 2, 1, 0], ________ )` 함수에 `goatdoors = [2, 1, 0, 2, 1]`를 인자로 호출한다면, 함수는 작동하지 않을 것입니다. `goatdoors` 인자 값에서 잘못된 부분의 의미(이유)를 설명하고, 작동할 수 있는 인자값(들)을 제시하십시오. 

#### 답:
```
- goatdoors [2, 2, 0, 2, 1] or [2, 0, 0, 2, 1]
```

## Step 5 - Almost finished...: 
Last function: write a `win_percentage` function that takes an array or list of `guesses` and `prizedoors`, and returns the percent of correct guesses

In [ ]:
#%%file win_percentage.py
# win_percentage.py
# CrushPython - MontyHall

def win_percentage(guesses, prizedoors):
    """ Return the win percentage between 0 and 100. 
    win_percentage is calculated by the percent of times that a simulation of 
        guesses is correct
    The parameters: 
    guesses is an array or list of guesses for each simulation
    prizedoors is an array or list of the location of prize for each simulation

    >>> print(win_percentage(np.array([0, 1, 2]), np.array([0, 0, 0])))
    33.333
    >>> print(win_percentage([0, 1, 2], [0, 0, 0]))
    33.333
    """
    
    wins = []
    winpercentage = []

    
    return winpercentage

# Congratulations!

## Step 5 - The final step: 
Now, put it together. Simulate (nsim=1000) games where contestant keeps his original guess versus where the contestant switches his door after a  goat door is revealed. 

Compute the percentage of time the contestant wins under either strategy. Is one strategy better than the other?

__A sample run:__
```
Winning Rate with the original guess: 0.324
Winning Rate with the switched guess: 0.647
```

In [ ]:
#%%file MontyHall.py
# MontyFall.py
# CrushPython - MontyHall

nsim = 1000



print("Winning Rate with the original guess:", win_percentage(guess, prizedoor))

#switch everytime for nsim



print("Winning Rate with the switched guess:", win_percentage(switchguess, prizedoor))

# Challenge: Plot the simulation process. 
As the number of simulation increases, the winning rate converges as we computed above. In the plot, the x-axis is the number of simulation, and the y-axis the winning rate.

__A sample run:__
<img src="https://github.com/idebtor/KMOOC-ML/blob/master/ipynb/images/montyhall_plot.png?raw=true" width="400">
<center>Monty Hall problem winning rate simulation</center>

In [ ]:
#%%file MontyHallPlot.py
# MontyFallPlot.py
# CrushPython - MontyHall

%matplotlib inline
import matplotlib.pyplot as plot

nsim = 1000    
win_rate_keep = []



plot.plot([x for x in range(1, nsim)], win_rate_keep, label='Original Guess')   

win_rate_swap = []
for n in range(1, nsim):

    
    
plot.plot([x for x in range(1, nsim)], win_rate_swap, label='Switched Guess')   
plot.title("Winning Rate Plot")
plot.xlabel("Number of Simulation")
plot.ylabel("Winning Percentage")
plot.legend() 

### Fianl Note:
Many people find this answer counter-intuitive (famously, PhD mathematicians have incorrectly claimed the result must be wrong. Clearly, none of them knew Python). 

One of the best ways to build intuition about why opening a Goat door affects the odds is to re-run the experiment with 100 doors and one prize. If the game show host opens 98 goat doors after you make your initial selection, would you want to keep your first pick or switch? Can you generalize your simulation code to handle the case of `n` doors?

-----
God has saved us and called us to a holy life - not because of anythin we have done but because of his own purpose and grace. This grace was given us in Christ Jesus before the beginning of time. (1Tim1:9)

하나님이 우리를 구원하사 거룩하신 소명으로 부르심은 우리의 행위대로 하심이 아니요 오직 자기 뜻과 영원 전부터 그리스도 예수 안에서 우리에게 주신 은혜대로 하심이라. (딤후1:9)